- name: catalogue servwe-setup
  hosts: catalogue
  become: yes

  tasks:
  - name: disable default module nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create a roboshop user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: creat app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  
  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
     path: /app

  - name: copy catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: conecting to mongodb
    ansible.builtin.command: $(mongosh mongodb.zyna.space --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')")
    register: catalogue_output

  # - name: evaluuate catalogue db
  #   community.mongodb.mongodb_shell:
  #     login_host: mongodb.zyna
  #     eval: "db.getMongo().getDBNames().indexOf('catalogue')"
  #   register: catalogue_output
     


  - name: print catalogue db output
    ansible.builtin.debug:
      msg: "{{catalogue_output}}"

  - name: load products into mongodb
    ansible.builtin.shell: mongosh --host mongodb.zyna.psace </app/db/master-data.js