- name: setup mongodb server
  hosts: mongodb
  become: yes

  tasks:
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: vim /etc/yum.repos.d/mongo.repo
      
     
       