- name: redis
  hosts: redis
  become: yes

  tasks:
  - name: disable redis
    ansible.builtin.command: dnf module disable redis -y   
    #we use command mode because they is no module 
    #beoure that we need to check a complexity of command 

  - name: enable redis 7
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: installing redis
    ansible.builtin.package:
     name: redis
     state: present


  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

  - name: start and enable redis
    ansible.builtin.service:
     name: radise
     enabled: yes
     state: present
     
    
